name: "build"
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - name: install app dependencies and build it
      run: yarn install --frozen-lockfile && yarn build
    - name: download vosk model
      run: |
        VOSK_MODEL_VERSION=0.22
        curl -LO https://alphacephei.com/vosk/models/vosk-model-ja-$VOSK_MODEL_VERSION.zip
        mkdir ./src-tauri/resources
        mv vosk-model-ja-$VOSK_MODEL_VERSION.zip ./src-tauri/resources
        unzip ./src-tauri/resources/vosk-model-ja-$VOSK_MODEL_VERSION.zip
        rm vosk-model-ja-$VOSK_MODEL_VERSION.zip
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "App v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
        args: --target universal-apple-darwin
